### ISSUE TITLE
send survey

### ISSUE THREAD

**Issue by shimont** [aws-ug-israel/meetup#9]
https://www.typeform.com/

**Comment by TalHibner** [comment]
Survey: How was the Israel AWS User Group meetup #81 last week ???
---------------------------------------------------------------------------------

Thank you all for coming last week to the meetup #81 Production Engineering on AWS !

We would like to get feedbacks, in order to make more interesting content, and better experience in general.

Please help us and answer the following survey of 10 questions:

https://www.surveymonkey.com/r/5VC5SN7

Best,

AWS User Group Israel Team
